### ISSUE TITLE
Results don't match the provided reference

### ISSUE THREAD

**Issue by Funhador** [francescamen/SHARP#2]
Dear @francescamen,

Thanks for the work carried out. I have been having problems validating your article's result and I was wondering if you could give me some insights. 

After training the network, testing it with any other dataset except the one generated from the same set of Doppler traces used for training results in highly different accuracies and F1-scores from the ones shown in the paper. However, a warning from the scikit-learn is raised for undefined metrics (as shown in the attached image).  As this warning doesn't appear in the exception I mentioned, I believe the problem is related to this but until now I've been fruitless in finding its root.
![UndefinedMetricWarning](https://user-images.githubusercontent.com/54557754/237057540-f5ad4ae2-ff32-4f4e-a9b4-bf8b2b3c5ebd.PNG)

**Comment by francescamen** [comment]
Dear @Funhador,

I rechecked my code and dataset and I was able to replicate the results of the paper. 
I created a shared folder where I uploaded the pre-computed Doppler traces, you can find the link in the repository README at https://github.com/francescamen/SHARP/tree/main#pre-computed-doppler-traces
In the same folder, I uploaded some plots of Doppler traces and some confusion matrices obtained through the pre-trained model. 

I also uploaded a new file in this repository to visualize the Doppler traces, please see https://github.com/francescamen/SHARP#doppler-computation. 

Can you please try to run the code with those pre-computed Doppler traces to see whether you can replicate the results? 

Thank you for your feedback!
Francesca

**Comment by SMuzamilAli** [comment]
Dear @francescamen,

I hope this message finds you well. My name is Syed Muzammil Ali, and I am currently working with your codebase to replicate your work.

While executing the code in the file CSI_phase_sanitization_H_estimation.py, I encountered the following error related to the plots_utility.py module:

python
Copy code
Traceback (most recent call last):
  File "C:\Users\Alis\Downloads\Muzammil\SHARP\Python_code\CSI_phase_sanitization_H_estimation.py", line 21, in <module>
    from plots_utility import *
  File "C:\Users\Alis\Downloads\Muzammil\SHARP\Python_code\plots_utility.py", line 27, in <module>
    rcParams['text.latex.preamble'] = [r'\usepackage{newtxmath}']
  File "C:\Users\Alis\AppData\Roaming\Python\Python311\site-packages\matplotlib\__init__.py", line 747, in __setitem__
    raise ValueError(f"Key text.latex.preamble: {ve}") from None
ValueError: Key text.latex.preamble: Could not convert ['\\usepackage{newtxmath}'] to str
It seems that there's an issue with the conversion of the LaTeX preamble string. Specifically, the line rcParams['text.latex.preamble'] is causing a ValueError. The error suggests that the value ['\\usepackage{newtxmath}'] cannot be converted to a string.

I would appreciate it if you could provide some guidance on how to resolve this issue. If there have been any recent changes to the code that might have caused this problem, or if there are specific dependencies or configurations that need attention, please let me know.

Thank you for your assistance, and I look forward to hearing from you soon.

Best regards,
Syed Muzammil Ali

**Comment by riverleejames** [comment]
Subject: Issue Replicating Paper Results with Pre-computed Doppler Traces

Dear @francescamen ,

Like @Funhador , I encountered difficulties in replicating the results presented in your paper, despite using the pre-computed Doppler traces you provided. Wondering if this might be due to library updates, I meticulously set up a Docker container with the exact library versions specified in your instructions. Unfortunately, I still ended up with the same outcomes.

Please see results below: 
[cm_complete_different_E,L,W,R,J_S7a_band_80_subband_1.pdf](https://github.com/francescamen/SHARP/files/15067631/cm_complete_different_E.L.W.R.J_S7a_band_80_subband_1.pdf)

[cm_complete_different_E,L,W,R,J_S7a_band_80_subband_1_max_merge.pdf](https://github.com/francescamen/SHARP/files/15067632/cm_complete_different_E.L.W.R.J_S7a_band_80_subband_1_max_merge.pdf)

Compared to the results you provided: 
[cm_complete_different_E,L,W,R,J_S7a_band_80_subband_1.pdf](https://github.com/francescamen/SHARP/files/15067652/cm_complete_different_E.L.W.R.J_S7a_band_80_subband_1.pdf)
[cm_complete_different_E,L,W,R,J_S7a_band_80_subband_1_max_merge.pdf](https://github.com/francescamen/SHARP/files/15067653/cm_complete_different_E.L.W.R.J_S7a_band_80_subband_1_max_merge.pdf)

Thank you, 

River.

**Comment by francescamen** [comment]
Dear @riverleejames, I am sorry for my late reply, I missed the notification regarding your issue. 

I checked the code and I think the issue is linked to the optimizer I used during phase sanitization to obtain the CFR to be used for Doppler computation. In my previous version of the code, I used the CVXPY library while I updated the code to directly use OSQP in the version that is online now. The OSQP version is way faster but apparently produces slightly different results. I uploaded in the shared Google Drive folder (https://drive.google.com/drive/folders/1SilO6VD73Lz8sjZ-KQgFnQ2IKRvggqPg?usp=sharing) a compressed file (Python_code_old.zip) containing the previous version of the code that uses the CVXPY solver. Can you try to use this version of the code? This should allow you to reproduce the results. Please, take a look at the README file inside the zip file for information on how to run the code.

Please, let me know if you can solve the issue in this way.
Best, 
Francesca
