### ISSUE TITLE
Duplicate and Inconsistent Doppler Trace Files

### ISSUE THREAD

**Issue by Oriseven** [francescamen/SHARP#3]
Dear @francescamen,

I am currently working with the Doppler trace data you provided via Google Drive and have encountered some issues that I hope can be clarified or resolved.

1. Duplicate Files: I noticed that the following three Doppler trace files appear to be identical: S4a-L, S5a-L, S5a-LOS
![image](https://github.com/francescamen/SHARP/assets/71508703/6d711efa-3b33-45be-9feb-10b30228bbff)

It seems unusual that the values of these files are exactly the same, considering they are collected under different environments. 

2. Inconsistency with Reproduced Doppler:
When using the code you provided to generate Doppler traces for S4a-L and S5a-L, the output I obtained was significantly different from the traces you provided. Not only are the traces dissimilar in terms of data values, but the length of the data also different.

Doppler trace for S4a-L:
![image](https://github.com/francescamen/SHARP/assets/71508703/38987ee5-3014-47ac-8108-d519d74a7719)

Doppler trace for S5a-L:
![image](https://github.com/francescamen/SHARP/assets/71508703/d8a1a03d-8afe-471d-8cc0-94f57cd429ac)

I have successfully replicated similar Doppler traces for other data sets using the same code, which suggests that the code usage on my end is correct. Could you please check and confirm the integrity and correctness of the files? Your assistance in resolving these issues would be greatly appreciated.

**Comment by XGBoost** [comment]
I have the same problem~

**Comment by francescamen** [comment]
Dear @Oriseven, @XGBoost, 

Sorry for not getting back to you earlier. I answer your two points next. 

1. I checked the code and I confirm that the files S4a-L, S5a-L, S5a-LOS for the different streams are the same. For what concerns S5a-L, S5a-LOS it's only because I renamed all the files to L and forgot to remove the LOS files. Regarding S4a-L I'll check shortly and let you know, I think also this is linked with the naming of the files as the plots have exactly the same checksum.

2. This is the same issue that another person experienced and I looked into it. It seems related to the optimizer as I changed it to make the algorithm faster but it is not providing the same results as the previous one. Can you please try using the old version of the code and see if you can reproduce the results with that? You can find all the information to do that in the following answer: https://github.com/francescamen/SHARP/issues/2#issuecomment-2306778077

Please, let me know if this solves the issue.
Thank you for your interest in the project!
Francesca

**Comment by francescamen** [comment]
Dear @Oriseven, @XGBoost, 

I updated the pictured with the correct ones. I also uploaded the Doppler traces for the S4_L and S5_L in a separated zip file in the shared Google Drive folder. 

Hope this helps, 
Francesca
